// @generated by protoc-gen-connect-es v0.12.0 with parameter "target=ts,import_extension=none"
// @generated from file chat.proto (package chat, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ConnectServerRequest, Message, SendMessageRequest } from "./chat_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service chat.Chat
 */
export const Chat = {
  typeName: "chat.Chat",
  methods: {
    /**
     * @generated from rpc chat.Chat.ConnectServer
     */
    connectServer: {
      name: "ConnectServer",
      I: ConnectServerRequest,
      O: Message,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc chat.Chat.SendMessage
     */
    sendMessage: {
      name: "SendMessage",
      I: SendMessageRequest,
      O: Message,
      kind: MethodKind.Unary,
    },
  }
} as const;

